# Generated by Django 6.1 on 2026-08-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UCLStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('team', models.CharField(max_length=100)),
                ('match_played', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('losts', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('goals_conceded', models.IntegerField()),
                ('gd', models.IntegerField()),
                ('group_point', models.IntegerField()),
                ('champions', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'UCL Statistic',
                'verbose_name_plural': 'UCL Statistics',
            },
        ),
    ]
